Repository rewiringamerica/incentives-visualizer, pull requests merged in 2025-04, with the labels that each got.

#65 Implemented incentive filters and redesigned UI
  src/components/IncentivesFilter.tsx
  src/components/Sidebar.tsx
  src/mocks/data.ts
  test/sidebar.test.tsx
Labels: enhancement, Medium

#70 Fixed zoom and refactored state abbreviations
  src/components/Counties.tsx
  src/components/MapButtons.tsx
  src/components/Sidebar.tsx
  src/components/States.tsx
  src/data/abbrevsToFull.tsx
Labels: Easy

#68 Add searching by state functionality
  src/components/App.tsx
  src/components/Map.tsx
  src/components/Navbar.tsx
  src/components/States.tsx
  src/data/states.ts
Labels: Must Have, Easy, P1

#71 Grouped filters by incentive categories
  src/components/Sidebar.tsx
  src/data/incentiveCategories.ts
Labels: enhancement, P3

#78 Create highlights + refactor state/county data selection
  src/components/App.tsx
  src/components/Counties.tsx
  src/components/Map.tsx
  src/components/MapHighlights.tsx
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/components/States.tsx
  test/sidebar.test.tsx
  tsconfig.json
Labels: Must Have, Easy

#75 Added search by county
  src/components/App.tsx
  src/components/Counties.tsx
  src/components/Navbar.tsx
Labels: Must Have, Easy, P1

#83 Removes state and county name tooltip upon hover
  src/components/Counties.tsx
  src/components/States.tsx
Labels: enhancement, Easy, P3

#91 Restructured zoom levels and buttons
  src/components/Counties.tsx
  src/components/Map.tsx
  src/components/MapLabels.tsx
  src/components/States.tsx
  src/components/ZoomControls.tsx
  src/components/icons.tsx
Labels: enhancement, P3

#98 Updated documentation
  DEVELOPMENT.md
  README.md
Labels: documentation
