Repository rewiringamerica/incentives-visualizer, pull requests merged in 2025-02, with the labels that each got.

#18 Initializing Map and React Project
  .gitignore
  .postcssrc
  package-lock.json
  package.json
  src/components/Map.tsx
  src/index.html
  src/styles/index.css
Labels: P1

#20 Initialize openapi
  package-lock.json
  package.json
  src/lib/api.ts
  src/types/api.gen.ts
Labels: enhancement

#37 Restrict Map Bounds & Add Inset Buttons
  package.json
  src/components/Map.tsx
  src/components/MapButtons.tsx
  yarn.lock
Labels: enhancement, P1

#39 Added info sidebar component and improved UI
  src/assets/logo.png
  src/assets/placeholder_icon.png
  src/components/App.tsx
  src/components/Map.tsx
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/components/States.tsx
  src/index.html
Labels: enhancement, Must Have, P1

#40 Feat/map legend - Implemented map legend UI following map style and updating from layers on map
  .env.template
  package.json
  src/components/Legend.tsx
  src/components/Map.tsx
  yarn.lock
Labels: enhancement, P1

#35 Added mock data implementation
  src/mocks/README.md
  src/mocks/data.ts
  src/mocks/types.ts
Labels: documentation, P1
