Repository rewiringamerica/incentives-visualizer, pull requests merged in 2025-03, with the labels that each got.

#49 Adds slide-in/out animation to sidebar
  package.json
  src/components/App.tsx
  src/components/Sidebar.tsx
  yarn.lock
Labels: Easy

#47 Add formatter
  .prettierignore
  .prettierrc
  README.md
  package.json
  src/components/App.tsx
  src/components/Legend.tsx
  src/components/Map.tsx
  src/components/MapButtons.tsx
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/components/States.tsx
  src/components/card.tsx
  src/components/icons.tsx
  src/components/incentive-card.tsx
  src/index.html
  src/lib/api.ts
  src/mocks/data.ts
  src/mocks/types.ts
  src/styles/index.css
  yarn.lock
Labels: enhancement, P2

#54 Test/add tests
  .github/workflows/playwright.yml
  .github/workflows/vitest.yml
  .gitignore
  package.json
  playwright.config.ts
  src/components/Map.tsx
  src/data/states.ts
  test/e2e/map.test.ts
  test/setup.js
  test/sidebar.test.tsx
  tsconfig.json
  vitest.config.ts
  yarn.lock
Labels: Must Have, P1

#57 Updated state coverage colors and legend
  src/components/Legend.tsx
  src/components/States.tsx
  src/data/abbrevsToFull.tsx
Labels: P1

#55 ci: add lint workflow file
  .github/workflows/ci.yml
  package.json
Labels: Easy, P1
